/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sistemas;

import java.util.Scanner;

public class App {
    
Scanner sc = new Scanner(System.in);

    // Diseñe un algoritmo para saludar al usuario: Hola usuario. El nombre del usuario es ingresado por teclado
    public static String saludarUsuario(String nombre) {
        try {
        return "Hola " + nombre;
        } catch (Exception e) {
            return "Error: " + e.getMessage();
        }
    }

    // Diseñe un algoritmo que lea por teclado una velocidad en Km/seg y la convierta a metros/seg y a metros/hora
    // retorne el valor en formato string (metrosPorSeg + "|" + metrosPorHora)
    public static String convertirVelocidad(double kmPorSeg) {
        try {
            long metrosPorSeg = (long) (kmPorSeg * 1000);
            long metrosPorHora = (long) (metrosPorSeg * 3600); 
            return String.format("%d|%d", metrosPorSeg, metrosPorHora);
        } catch (Exception e) {
        return "0|0";
        }
    }

    // Solicitar al usuario ingresar una cantidad expresada en cc (centímetros cúbicos) y devolver su cantidad en litros
    public static int convertirCcALitros(double cc) {
        try {
            int litros = (int) (cc / 1000);
            return litros;
        } catch (Exception e) {
            return -1;
        }
    }

    // Solicitar al usuario ingresar una cantidad en dólares y convertirla a pesos según la TRM del día
    public static int convertirDolaresAPesos(double dolares, double trm) {
        try {
            int pesos = (int) (dolares * trm);
            return pesos;
        } catch (Exception e) {
            return -1;
        }
    }

    // Solicitar al usuario ingresar la temperatura en grados celsius y convertirla en grados Fahrenheit (averiguar la fórmula) F = 32 + ( 9 * C / 5)
    public static int convertirCelsiusAFahrenheit(double celsius) {
        try {
            int Fahrenheit = (int) (32 + (9*celsius / 5));
            return Fahrenheit;
        } catch (Exception e) {
            return -1;
        }
    }

    // Solicitar al usuario ingresar Nro de Días nro de horas nro de minutos y nro segundos y convertir todo a segundos.
    public static int convertirATotalSegundos(int dias, int horas, int minutos, int segundos) {
        try {
            int conversionSegundos = (dias * 86400) + (horas * 3600) + (minutos * 60) + segundos;
            return conversionSegundos; 
        } catch (Exception e) {
            return -1;
        }
    }

    // Un usuario tiene un sistema de báscula para pesar camiones, dado el peso de un camión debe sacar el peso neto de la carga en kilos y toneladas
    // retorne el valor en formato string (pesoEnKg + "|" + pesoEnToneladas)
    public static String calcularPesoNeto(double peso) {
        try {
            //se asume que la bascula arroja el peso en kg
            int pesoEnKg = (int) peso;
            int pesoToneladas = (int) (peso / 1000);
            return String.format("%d|%d",pesoToneladas, pesoEnKg);
        } catch (Exception e) {
            return "0|0";
        }
    }

    // Diseñe un algoritmo que calcule el tiempo necesario para alcanzar un destino dado por el usuario quien además ingresará la velocidad promedio en kilómetros/hora y la distancia en kilómetros
    public static int calcularTiempoViaje(double distancia, double velocidadKilometros, double velocidadHora) {
        if (velocidadKilometros  == 0) {
            return -1;
        }
            try {
            double velocidad = (velocidadKilometros / velocidadHora);
            double tiempo = (distancia / velocidad);
            return (int) tiempo;
        } catch (Exception e) {
            return -1;}
        }
    // Un avión necesita cargar combustible para cubrir sus rutas programadas en el día. Cada 0.2 toneladas de combustible puede recorrer 60.8 Km en velocidad de crucero. En el despegue el avión consume 1.2 toneladas de combustible y en el aterrizaje consume 0.4 toneladas. El piloto desea un algoritmo que ingresando 4 rutas y el kilometraje de cada ruta obtenga la cantidad de combustible que debe tanquear en el avión.
    public static int calcularCombustible(double ruta1, double ruta2, double ruta3, double ruta4) {
        try {
            double rutas = ((ruta1 + ruta2 + ruta3 + ruta4) / 304);
            double despegues = (1.2 * 4);
            double aterrizajes = (0.4 * 4);
         double combustibe_a_tanquear = (rutas + despegues + aterrizajes);
         return (int) combustibe_a_tanquear;
        } catch (Exception e) {
            return -1;
        }
    }

    // Diseñar un algoritmo que calcule el peso neto en la luna de un peso terrestre ingresado por teclado. La gravedad de la Luna es de alrededor del 17% más que la de la tierra
    public static int calcularPesoLunar(double pesoTierra) {
        try {
            int pesoLuna = (int) ((pesoTierra / 9.81) * 1.62);
            return pesoLuna;
        } catch (Exception e) {
            return -1;
        }
    }

    // Diseñar un algoritmo que calcule el saldo que debe haber en una taquilla de un banco. El cajero deberá ingresar la base el total de recaudos y el total de retiros
    public static int calcularSaldoTaquilla(double base, double ingresos, double retiros) {
        try {
            int taquillaFinal = (int) (base + ingresos - retiros);
            return taquillaFinal;
        } catch (Exception e) {
            System.out.println("Dato Invalido");
            return -1;
        }
    }

    // Diseñe un algoritmo para calcular la propina en un restaurante(10%) el impuesto al consumo (8%) y el valor final que deberá pagar ingresando el valor de la comida.
    // retorne el valor en formato string (propina + "|" + impuesto + "|" + total)
    public static String calcularCuentaRestaurante(double costoComida) {
        try {
            int propina = (int) (costoComida * 0.1);
            int impuesto = (int) (costoComida * 0.08);
           int valorFinal = (int) (costoComida + propina + impuesto);
           return String.format("%d|%d|%d", propina, impuesto, valorFinal);
        } catch (Exception e) {
            return -1 + "|" + -1 + "|" + -1;
        }
    }

    // Diseñar un algoritmo que obtenga los puntos finales de un equipo de fútbol (puntuación según lineamientos de Fifa) a partir de los datos ingresados por teclado: Número de partidos ganados número de partidos perdidos número de partidos empatados.
    public static int calcularPuntosFutbol(int ganados, int perdidos, int empatados) {
        try {
            int puntosFinales = (ganados * 3 + empatados);
            return puntosFinales;
        } catch (Exception e) {
            return -1;
        }
    }

    // Elaborar un algoritmo que dadas todas las 5 notas y los 5 porcentajes para una materia calcule la nota final.
    public static int calcularNotaFinal(double nota1, double nota2, double nota3, double nota4, double nota5, double porcentaje1, double porcentaje2, double porcentaje3, double porcentaje4, double porcentaje5) {                              
        try {
            if (porcentaje1 == 0 && porcentaje2 == 0 && porcentaje3 == 0 && porcentaje4 == 0 && porcentaje5 == 0) {
                return -1;
            }   
        double notaFinalUno = (nota1 * porcentaje1);
        double notaFinalDos = (nota2 * porcentaje2);
        double notaFinalTres = (nota3 * porcentaje3);
        double notaFinalCuatro = (nota4 * porcentaje4);
        double notaFinal = notaFinalUno + notaFinalDos + notaFinalTres + notaFinalCuatro;
        return (int) Math.ceil(notaFinal);
        
        } catch (Exception e) {
            return -1;
        }
    }

    // Elaborar un algoritmo que dados los 5 porcentajes de una materia y las 4 primeras notas calcule cuánto tiene que sacar para ganar si el puntaje mínimo es 3.
    public static int calcularNotaNecesaria(double porcentaje1, double porcentaje2, double porcentaje3, double porcentaje4, double porcentaje5, double nota1, double nota2, double nota3, double nota4) {
        try {
            if (porcentaje1 == 0 && porcentaje2 == 0 && porcentaje3 == 0 && porcentaje4 == 0 && porcentaje5 == 0) {
                return -1;
            }
            double notaFinalUno = (nota1 * porcentaje1);
            double notaFinalDos = (nota2 * porcentaje2);
            double notaFinalTres = (nota3 * porcentaje3);
            double notaFinalCuatro = (nota4 * porcentaje4);
            double notaFinal = notaFinalUno + notaFinalDos + notaFinalTres + notaFinalCuatro;
            double notaObjetivo = 3;
            double notaObtener = ((notaObjetivo - notaFinal) / porcentaje5);
            return (int) Math.ceil(notaObtener);
        } catch (Exception e) {
            return -1;
        }
    }

    // Se requiere un algoritmo para calcular el salario a pagar a un trabajador con los siguientes datos ingresados por teclado: cantidad de horas normales laboradas cantidad de horas extras diurnas laboradas cantidad de horas extras nocturnas laboradas valor de la hora normal. El valor de las horas extras diurnas tienen un recargo adicional del 15% sobre la hora normal. El valor de las horas extras nocturnas tienen un recargo adicional del 35% sobre la hora normal.
    public static int calcularSalario(int horasNormales, int horasExtrasDiurnas, int horasExtrasNocturnas, double valorHoraNormal) {
        try {
            if (horasNormales == 0 && horasExtrasDiurnas == 0 && horasExtrasNocturnas == 0 && valorHoraNormal == 0) {
                return -1;
            }
         double valorHorasExtrasDiurnas = horasExtrasDiurnas * (valorHoraNormal * 1.15);
         double valorHorasExtrasNocturnas = horasExtrasNocturnas * (valorHoraNormal * 1.35);
         double valorHorasNormales = horasNormales * valorHoraNormal;
         double valorTotal = valorHorasNormales + valorHorasExtrasDiurnas + valorHorasExtrasNocturnas;
         return (int) valorTotal; 

        } catch (Exception e) {
            return -1;
        }
        }    

    // Diseñe un algoritmo que calcule el área de un triángulo rectángulo.
    public static int calcularAreaTriangulo(double base, double altura) {
        try {
      return (int) ((base * altura)/2);
        } catch (Exception e) {
            return -1;
        }
    }

    // Diseñe un algoritmo que calcule el perímetro de un cuadrado.
    public static int calcularPerimetroCuadrado(double lado) {
        try {
        return (int) (lado * 4);
        } catch (Exception e) {
            return -1;
        }
    }

    // Diseñe un algoritmo que calcule el volumen de un cilindro.
    public static int calcularVolumenCilindro(double radio, double altura) {
        try {
            double volumenCilindro = (Math.PI * Math.pow(radio,2) * altura);
            return (int) volumenCilindro;
        } catch (Exception e) {
            return -1;
        }
    }

    // Diseñe un algoritmo que calcule el área del círculo. El radio se pide por teclado.
    public static int calcularAreaCirculo(double radio) {
        try {
            return (int) (Math.PI * Math.pow(radio,2));
        } catch (Exception e) {
            return -1;
        }
    }

    public static void main(String[] args) {
        
    }
}

